### ISSUE TITLE
Formato de imágen incorrecto

### ISSUE THREAD

**Issue by Villanueva-Flavio** [gcc-cdimatteo/Introduccion-a-los-Sistemas-Distribuidos-75.43#1]
Buenas, quería comentar que la carpeta **2023C1-C-NT** que contiene las fotos en formato .png
No son formato .png, son formato .HEIC, se soluciona volviéndolo a colocar como .HEIC y usando alguna herramienta para hacer la conversión (usé: www.iloveimg.com como test)

**Comment by gcc-cdimatteo** [comment]
Buenas! No es un formato incorrecto. Es la compresión de iOS. Efectivamente tenés que usar un converso para pasarlas a png. Voy a sumar el link en los links de interés para los que tengan el mismo problema. Gracias!
